apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: miniodata
  name: miniodata
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
