version: '3.1'

services:
  task-manager:
    build:
      context: ./task-manager
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "${DB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodbdata:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "${EXPRESS_PORT}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}"
    depends_on:
      - mongo

  minio:
    image: bitnami/minio
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_UI_PORT}:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root-root
      MINIO_DEFAULT_BUCKETS: images
    volumes:
      - miniodata:/data


volumes:
  mongodbdata:
  miniodata:
