apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-plain.yml
      --out ./kompose/
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: subtask-manager
  name: subtask-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: subtask-manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-plain.yml
          --out ./kompose/
        kompose.version: 1.21.0 (992df58d8)
      labels:
        io.kompose.service: subtask-manager
    spec:
      containers:
      - env:
        - name: CURRENT_ENV
          value: docker
        image: alecava41/subtask-manager:54ed31c62f55
        imagePullPolicy: ""
        name: subtask-manager
        ports:
        - containerPort: 27017
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
