apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose-plain.yml
      --out ./kompose/
    kompose.version: 1.21.0 (992df58d8)
  labels:
    io.kompose.service: task-manager
  name: task-manager
spec:
  type: NodePort # TODO just for debug
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: task-manager
